version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
    volumes:
      - .:/app
    command: >
      fastapi dev main.py --host 0.0.0.0

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes: --r
      - mongodb_data:/data/db

volumes:
  mongodb_data:
